branches:
  only:
  - master
  - stable

language: node_js

node_js:
  - "10"

install:
  - npm ci

script:
  - npm run build

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "robotics-club-cit"
